// AUTH
export const AUTH_START = "AUTH START";
export const AUTH_SUCCESS = "AUTH SUCCESS";
export const AUTH_FAILED = "AUTH FAILED";
export const LOGOUT_SUCCESS = "LOGOUT SUCCESS";
export const TOGGLE_AUTH = "TOGGLE AUTH";

//RECIPE
export const GET_RECIPES = "GET RECIPES";
export const GET_RECIPES_SUCCESS = "GET RECIPES SUCCESS";
export const GET_USER_RECIPES = "GET USER RECIPES";
export const GET_USER_RECIPES_SUCCESS = "GET USER RECIPES SUCCESS";
export const GET_SINGLE_RECIPE_SUCCESS = "GET SINGLE RECIPE SUCCESS";
export const ADD_RECIPE_INIT = "ADD RECIPE INIT";
export const ADD_RECIPE = "ADD RECIPE";
export const ADD_RECIPE_SUCCESS = "ADD RECIPE SUCCESS";
export const LOADING = "LOADING";
export const ERROR_OCCURED = "ERROR_OCCURED";